global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rag_service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['rag-service:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']